// Code generated by go-swagger; DO NOT EDIT.

package output

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jsam/udebug-cli/models"
)

// GetOutputAPIOutputRetrieveJSONReader is a Reader for the GetOutputAPIOutputRetrieveJSON structure.
type GetOutputAPIOutputRetrieveJSONReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOutputAPIOutputRetrieveJSONReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetOutputAPIOutputRetrieveJSONOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetOutputAPIOutputRetrieveJSONOK creates a GetOutputAPIOutputRetrieveJSONOK with default headers values
func NewGetOutputAPIOutputRetrieveJSONOK() *GetOutputAPIOutputRetrieveJSONOK {
	return &GetOutputAPIOutputRetrieveJSONOK{}
}

/*GetOutputAPIOutputRetrieveJSONOK handles this case with default header values.

OK
*/
type GetOutputAPIOutputRetrieveJSONOK struct {
	Payload models.ArrayOfString
}

func (o *GetOutputAPIOutputRetrieveJSONOK) Error() string {
	return fmt.Sprintf("[GET /output_api/output/retrieve.json][%d] getOutputApiOutputRetrieveJsonOK  %+v", 200, o.Payload)
}

func (o *GetOutputAPIOutputRetrieveJSONOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
