// Code generated by go-swagger; DO NOT EDIT.

package output

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jsam/udebug-cli/models"
)

// PostOutputAPIPostCustomInputOutputJSONReader is a Reader for the PostOutputAPIPostCustomInputOutputJSON structure.
type PostOutputAPIPostCustomInputOutputJSONReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostOutputAPIPostCustomInputOutputJSONReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostOutputAPIPostCustomInputOutputJSONOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostOutputAPIPostCustomInputOutputJSONOK creates a PostOutputAPIPostCustomInputOutputJSONOK with default headers values
func NewPostOutputAPIPostCustomInputOutputJSONOK() *PostOutputAPIPostCustomInputOutputJSONOK {
	return &PostOutputAPIPostCustomInputOutputJSONOK{}
}

/*PostOutputAPIPostCustomInputOutputJSONOK handles this case with default header values.

OK
*/
type PostOutputAPIPostCustomInputOutputJSONOK struct {
	Payload models.ArrayOfString
}

func (o *PostOutputAPIPostCustomInputOutputJSONOK) Error() string {
	return fmt.Sprintf("[POST /output_api/post_custom_input/output.json][%d] postOutputApiPostCustomInputOutputJsonOK  %+v", 200, o.Payload)
}

func (o *PostOutputAPIPostCustomInputOutputJSONOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
