// Code generated by go-swagger; DO NOT EDIT.

package input

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jsam/udebug-cli/models"
)

// GetInputAPIInputListRetrieveJSONReader is a Reader for the GetInputAPIInputListRetrieveJSON structure.
type GetInputAPIInputListRetrieveJSONReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInputAPIInputListRetrieveJSONReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetInputAPIInputListRetrieveJSONOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetInputAPIInputListRetrieveJSONOK creates a GetInputAPIInputListRetrieveJSONOK with default headers values
func NewGetInputAPIInputListRetrieveJSONOK() *GetInputAPIInputListRetrieveJSONOK {
	return &GetInputAPIInputListRetrieveJSONOK{}
}

/*GetInputAPIInputListRetrieveJSONOK handles this case with default header values.

OK
*/
type GetInputAPIInputListRetrieveJSONOK struct {
	Payload models.ArrayOfInput
}

func (o *GetInputAPIInputListRetrieveJSONOK) Error() string {
	return fmt.Sprintf("[GET /input_api/input_list/retrieve.json][%d] getInputApiInputListRetrieveJsonOK  %+v", 200, o.Payload)
}

func (o *GetInputAPIInputListRetrieveJSONOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
