// Code generated by go-swagger; DO NOT EDIT.

package input

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new input API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for input API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetInputAPIInputListRetrieveJSON gets list of inputs
*/
func (a *Client) GetInputAPIInputListRetrieveJSON(params *GetInputAPIInputListRetrieveJSONParams, authInfo runtime.ClientAuthInfoWriter) (*GetInputAPIInputListRetrieveJSONOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetInputAPIInputListRetrieveJSONParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetInputAPIInputListRetrieveJSON",
		Method:             "GET",
		PathPattern:        "/input_api/input_list/retrieve.json",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetInputAPIInputListRetrieveJSONReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetInputAPIInputListRetrieveJSONOK), nil

}

/*
GetInputAPIInputRetrieveJSON gets input
*/
func (a *Client) GetInputAPIInputRetrieveJSON(params *GetInputAPIInputRetrieveJSONParams, authInfo runtime.ClientAuthInfoWriter) (*GetInputAPIInputRetrieveJSONOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetInputAPIInputRetrieveJSONParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetInputAPIInputRetrieveJSON",
		Method:             "GET",
		PathPattern:        "/input_api/input/retrieve.json",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetInputAPIInputRetrieveJSONReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetInputAPIInputRetrieveJSONOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
