// Code generated by go-swagger; DO NOT EDIT.

package hint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new hint API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for hint API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetHintAPIHintListRetrieveJSON gets list of hints for problem
*/
func (a *Client) GetHintAPIHintListRetrieveJSON(params *GetHintAPIHintListRetrieveJSONParams, authInfo runtime.ClientAuthInfoWriter) (*GetHintAPIHintListRetrieveJSONOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetHintAPIHintListRetrieveJSONParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetHintAPIHintListRetrieveJSON",
		Method:             "GET",
		PathPattern:        "/hint_api/hint_list/retrieve.json",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetHintAPIHintListRetrieveJSONReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetHintAPIHintListRetrieveJSONOK), nil

}

/*
GetHintAPIHintRetrieveJSON gets hint
*/
func (a *Client) GetHintAPIHintRetrieveJSON(params *GetHintAPIHintRetrieveJSONParams, authInfo runtime.ClientAuthInfoWriter) (*GetHintAPIHintRetrieveJSONOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetHintAPIHintRetrieveJSONParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetHintAPIHintRetrieveJSON",
		Method:             "GET",
		PathPattern:        "/hint_api/hint/retrieve.json",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetHintAPIHintRetrieveJSONReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetHintAPIHintRetrieveJSONOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
